swagger: '2.0'
info:
  version: '1.1.0'
  title: Starr Assist - Rating API
  description: |
    Get rates for the Starr Assist Travel plans. 
    
    New Features:
    1. Added CFAR Premium even if CFAR is not opted
    2. Similary added TripCancellation Premium even if CFAR is opted
  
    Features:
    1. Accept input as JSON request with Plan information
    2. Respond back with premium information
    3. Respond with erorr message incase of invalid request or failure scenarios
    4. Added coverage information along with response
    5. Enhaced Rate API to respond with proper error messages
    
  contact:
    name: Adheep M
    email: adheep_m@solartis.net
host: starrassistuatkb.uat.solartis.net
basePath: /DroolsV4_2/DroolsService
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /FireEventV2:
    post:
      description: Get Rates for the given input
      operationId: getRates
      produces:
        - application/json
      parameters:
        - name: Token
          in: header
          description: Authentication Token
          required: true
          type: string
          format: string
          default: "iMgdpnp436QjuYQ2tn9HU+SgJDsyFW8kDSoLHGwadQKpl/wr4yKoVMjkSfJB/FKqjFqrLmebBUqmHM/dVAMv+DDPaXOt/GY7mjWZXGT2z0ArRvyiojuQz8LrhVYihPok4SNftJWQa7rNrqjh5PWJcVbnbLVHo4e9WNp/4X9Sai/5LrKZ1J99H71yIi/9rXsAKhCk5lGzFaO3SXLwJluxpsUM+5MiljDi4NFM+/K0KPeUOuL8R2FZD9RobXBVvR7xPdH1oZ71jBgOmg59/75ugVgJ/35PRXWc1Emi9SPqQHHEmsD4AoH2xj45UGMY3hjx0sz/uABSHKxNwA8DwPTBS7jaN2XqKLCayPsSWHVH04XW+ZeDaw1iRLb/0euQfXT97fiPQgPQSjtDvxif6cFXZQX/BHYIcAUjZtdcuv098quieEPaIWri6DUFEIzf/uRM7R4itGHIU7/B0cMwwQNFhxjtMVAgSBq7Kw4a8kf5s+2XOip5XV3KeT5U4u8HX6/xdKxhpP8gLng6PoGj0MEnSugWYicqO81QJH2UISAaI3iDgNxzCSFmsAChwURz5g/RRmHqLknkxHh4lvFfjQGlTIfdNwW+CwHbg0EQFt/c/4M6CofYIAQVzElcVRih/j88U7EqGr8v1mrTPel1sBXl+auuXSlODNRoeDVogcqA1Fr9504oM1kbCEmrVIqjUxUmK9a8CWsZEjIYiNuY0KncVKuuXSlODNRoeDVogcqA1Foa9LkTsAlC3ItSy+gbt0NdLaJdXbWS8ClBkbddTRCbeWRNMZNDq/vS1JTb8FKCl5OsniK5MZQnMbZdqNHlqbv2WOw2j+jUU0BThnDgEX6XEjSt7SoS1Xd6+F4DyPRZsQbD7XGhOWwTgbKALHDL6LviA3K4dHjVKHv1xOd8L284LsWKpOWqHf8xYqRIiCHZgQEtSRZCdfQPbklkXKGNaTjD"
        - name: EventName
          in: header
          description: Name of the event to be invoked
          required: true
          type: string
          format: string
          default: "InvokeRatingV2"
        - name: Rating
          in: body
          description: Rating content
          required: true
          schema:
            $ref: '#/definitions/Rating_Request'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/Rating_Success_Response'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  Rating_Request:
    type: object
    required:
     - ServiceRequestDetail
     - QuoteInformation
    properties:
      EndClientUserUniqueSessionId:
        type: string
      EndClientUserBrowserSessionId:
        type: string
      EndClientUserBrowserInformation:
        type: string
      PaaSClientIPAddress:
        type: string
      ClientUniqueRequestID:
        type: string
      ServiceRequestDetail:
        type: object
        required:
          - OwnerId
          - RegionCode
          - Token
          - ServiceRequestVersion
          - ServiceResponseVersion
          - ResponseType
        properties:
          ServiceRequestVersion:
            type: string
            default: "1.0"
          ServiceResponseVersion:
            type: string
            default: "1.0"
          OwnerId:
            type: string
            default: "15"
          ResponseType:
            type: string
            enum: ["JSON","XML"]
            default: "JSON"
          RegionCode:
            type: string
            default: "US"
          Token:
            type: string
            default: "iMgdpnp436QjuYQ2tn9HU+SgJDsyFW8kDSoLHGwadQKpl/wr4yKoVMjkSfJB/FKqjFqrLmebBUqmHM/dVAMv+DDPaXOt/GY7mjWZXGT2z0ArRvyiojuQz8LrhVYihPok4SNftJWQa7rNrqjh5PWJcVbnbLVHo4e9WNp/4X9Sai/5LrKZ1J99H71yIi/9rXsAKhCk5lGzFaO3SXLwJluxpsUM+5MiljDi4NFM+/K0KPeUOuL8R2FZD9RobXBVvR7xPdH1oZ71jBgOmg59/75ugVgJ/35PRXWc1Emi9SPqQHHEmsD4AoH2xj45UGMY3hjx0sz/uABSHKxNwA8DwPTBS7jaN2XqKLCayPsSWHVH04XW+ZeDaw1iRLb/0euQfXT97fiPQgPQSjtDvxif6cFXZQX/BHYIcAUjZtdcuv098quieEPaIWri6DUFEIzf/uRM7R4itGHIU7/B0cMwwQNFhxjtMVAgSBq7Kw4a8kf5s+2XOip5XV3KeT5U4u8HX6/xdKxhpP8gLng6PoGj0MEnSugWYicqO81QJH2UISAaI3iDgNxzCSFmsAChwURz5g/RRmHqLknkxHh4lvFfjQGlTIfdNwW+CwHbg0EQFt/c/4M6CofYIAQVzElcVRih/j88U7EqGr8v1mrTPel1sBXl+auuXSlODNRoeDVogcqA1Fr9504oM1kbCEmrVIqjUxUmK9a8CWsZEjIYiNuY0KncVKuuXSlODNRoeDVogcqA1Foa9LkTsAlC3ItSy+gbt0NdLaJdXbWS8ClBkbddTRCbeWRNMZNDq/vS1JTb8FKCl5OsniK5MZQnMbZdqNHlqbv2WOw2j+jUU0BThnDgEX6XEjSt7SoS1Xd6+F4DyPRZsQbD7XGhOWwTgbKALHDL6LviA3K4dHjVKHv1xOd8L284LsWKpOWqHf8xYqRIiCHZgQEtSRZCdfQPbklkXKGNaTjD"
          UserName:
            type: string
            default: "travelagent"
          LanguageCode:
            type: string
            default: "en"
          BrowserIp:
            type: string
      QuoteInformation:
        type: object
        required:
          - ProducerCode
          - OwnerId
          - PlanName
          - PlanCode
          - StateCode
          - EventName
          - ProductNumber
          - ProductVerNumber
          - TravelerList
        properties:
          ProductNumber:
            type: string
            default: "ILT"
          ProductVerNumber:
            type: string
            default: "1.0"
          ProducerCode:
            type: string
            default: "86201"
          OwnerId:
            type: string
            default: "15"
          PlanName:
            type: string
            enum: ["Air Ticket Protector","Classic Plus","Premier","Premier Annual","Basic Annual","Medical Only Annual","Renter's Collision"]
          PlanCode:
            type: string
            enum: ["1","2","3","4","9","10","11"]
          DepartureDate:
            type: string
            format: date
          ReturnDate:
            type: string
            format: date
          DepositDate:
            type: string
            format: date
          TripCancellationCoverage:
            type: string
            enum: ["","With Trip Cancellation","With Trip Cancellation for Any Reason"]
          DestinationCountry:
            type: string
          PolicyEffectiveDate:
            type: string
            format: date
          RentalStartDate:
            type: string
            format: date
          RentalEndDate:
            type: string
            format: date
          RentalLimit:
            type: string
            default: "35000"
          NumberOfRentalCars:
            type: string
            default: "1"
          StateCode:
            type: string
          QuoteType:
            type: string
            default: "New Business"
          EventName:
            type: string
            default: "InvokeRatingV2"
          TravelerList:
            type: array
            items:
              required:
                - TravelerDOB
              properties:
                TravelerDOB:
                  type: string
                  format: date
                TravelCost:
                  type: string
  Rating_Success_Response:
    type: object
    required:
      - RequestStatus
      - PremiumInformation
    properties:
      messageDetail:
        type: object
      RequestStatus:
        type: string
      PremiumInformation:
        type: object
        properties:
          TotalBasePremium:
            type: string
          TravelerList:
            type: array
            items:
              properties:
                TravelCost:
                  type: string
                TravelerDOB:
                  type: string
                  format: date
                TravelerBasePremium:
                  type: string
                TravelerGrossPremium:
                  type: string
                TravelerOptionalCoverage:
                  type: string
          PlanCode:
            type: string
          PlanName:
            type: string
          TotalGrossPremium:
            type: string
          TotalGrossPremium_IM:
            type: string
          ServierFee:
            type: string
          CommissionAmt:
            type: string
          TotalOptionalCoverage:
            type: string
          IsCFARApplicable:
            type: string
          TotalCFARPremium:
            type: string
          TotalTripCancellationPremium:
            type: string
      CoverageInformation:
        type: array
        items:
          properties:
            CoverageName:
              type: string
            CoverageLimit:
              type: string
            IsOptionalCoverage:
              type: string
  errorModel:
    type: object
    required:
      - RequestStatus
      - MessageDetail
    properties:
      RequestStatus:
        type: string
      MessageDetail:
        type: object
        properties:
          MessageCode:
            type: string
          MessageType:
            type: string
          UserMessage:
            type: string
          MessageLevel:
            type: string
          MessageSeverity:
            type: string
          MessageList:
            type: object
            properties:
              Message:
                type: array
                items:
                  type: string
