swagger: '2.0'
info:
  version: 1.0.0
  title: Solartis Authentication API for RSG
  description: >-
    Authentication API - is to generate a token which should be used in the Rate API. This token will be valid for the current day. The same token can be used for any number of Rate API tests during the day or you can choose to generate new token every time you want to test the Rate API.
host: alrcommonservice.uat.solartis.net
basePath: /CommonServiceV2_1/AuthenticationServiceV2
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /requestService:
    post:
      description: Get Authentication for RSG API
      operationId: getAuth
      produces:
        - application/json
      parameters:
        - name: Content-Type
          in: header
          description: Content Type
          required: true
          type: string
          format: string
          default: application/json
        - name: Authenticating Request
          in: body
          description: For authenticating request
          schema:
            $ref: '#/definitions/Authentication_Request'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/Authentication_Response'
        default:
          description: unexpected error
definitions:
  Authentication_Request:
    type: object
    properties:
      ServiceRequestDetail:
        type: object
        properties:
          OwnerId:
           title: OwnerId
           type: string
           default: '5'
          ResponseType:
            title: ResponseType
            type: string
            default: 'JSON'
          BrowserIp:
            title: BrowserIp
            type: string
            default: '192.168.5.98'
          ServiceRequestVersion:
            title: ServiceRequestVersion
            type: string
            default: '2.0'
      UserCredential:
        type: object
        properties:
          UserName:
           title: UserName
           type: string
           default: 'rateuser'
          Password:
            title: Password
            type: string
            default: 'DY/J+utxF/D2H2LqC4oQAw=='
  Authentication_Response:
    type: object
    properties:
      RequestStatus:
        type: string
        example: PROCESSED
      LoginStatus:
        type: string
        example: SUCCESS
      Token:
        type: string
        example: OdWuxizSblN/aMsyYuaGxiSFA6kDCViR/2dIRkmgdfQP6CtzNmvuw8AfYoijcoQiiXKYPZLvHUTfqQ06a9RvNhxK5AZjFjfv9j0f8WX6uL90Sp5ah4jaAql05yv3fy/UiubB2dfobYi1OX80hRdi6b4NjqlSCsVXgA7JY5noDIkwfuK2OFC5zObT1WzejIkr04du2FW4Ypg0ViwNkvpDSWAkn0zX6zo8egIHsKPH3NJWdvfIPYbiPkfBCTILYns+iT2MIlwVWrhGL4rOaGUptFiIvxj2SPtX/uSaBdTKooqXCMCc6I+VdSOE5qB1lVDvNdEOVJ6MineGZ/W1UHvunUzC+QQ99dwVWGkAe+Q5zsGrGmxV5hHGbl6QtC1Wfj4dN7W4yfuF2tdCh9gsYIz3YjFVYx8jkOI8ycrB19y6sM2xIpmmrcXwyHFG0Xd4E7QcDNMCTRVo6bVEGGtbPlHjm26Xg3nfw88mRSSbuTvJA4tzpPMHcIdBt5uZfS1C4WWMwUB7xAOmDYmdyw0R0vnXu7/T30UXHLrniJ4oIch24fzB+10tdosq+0zQnSs0vggLRbRRyaXqgbuLoT5FlzH/InY72Z3OS9Ghs/1p7BSIjDJ6KDZ0LqmX+1tPNvHKbQpa8G8thA961dSkU2Ttuk79A4+2rKL/ikMzi8af6qdA+2qr4DtfTNjxC442hjxp1221OjRCfc7ks+ihNPd8RSOEv4MCiZSK6k/PV8EYKJ7NkN9a9/2Z3vS8mEdzo4edFUqG/q87sOMrt4wx5yD9OX981x6RvOtrBIMK1MLZyMQXLdMCi0tPhIWnirpaQMKo0PRYjI4cetUTV2Llu6kM//Mz67lsci4SU+zGzZ7iHxrI4ts41OBwCmxLyR+5mYSNOV8Wq1mMP5LsTEt5qiLNVNG6zM01hCCQeBu7kTtAqZ3cONMTw3bWvxpNP8o9nqDHKizmHfnrBlPYpZUftL4lz6hAcYI0gqAhDmB8ceMyPpuvdNysYcuAlodw9kbN5RWzarIjHKG5wRcox5Lendj6A+6VPxTX+QpabdghC0qhZljls2zRG5WcKZkOeDKo+tcsoON5E/wkTUn12p1tb5/B/7kz3BAGpabQe4ow0T0lVKoq/5QLHO10Vg/5nWYkoul79KpOyn9hUAvp/isi0XaD5aLB6MWz2MfKcK6wLonoaO2BmAFVsw14/FtznsYCO4vrzAfR+++YfdvJMYtdLoXYNQR7WYGYwwvjkfM4qkQR/wt3Ei/483jNG0s0DAEiB48YWJtF34bu9B3XFT8bjuLutol0Afrzwed6kZY4E6dFCxOgZHXMe/VhKzPqEYidn+/zlqy9RWVlb2onyNPBH8QYedxatvY8B1Xr/xakmgjHGX+zod71pQBbjiVPhxLjzz5NrinLOpexADDJdYpWH1CF9sJn0wuP2VCGoe/ErKY2clf2l0PRNMpBdTYNK+EqLb/MMwqN/ieW1wmuvVVtXglAjgzOLLmw9kE2L086fcH/kG8aUUiShbjj5N/tusOSsAxCODRqfaH7oNTnqSCf1A3JOsJ0++6nZgoLSUkXut0LGY5d1q/5JJfOIlsvOk4inPyFUUZBmzfKdrX2ud1UUAEV/DWIUtrWG99VYfP8cPOBi2vZwT0YGE1/m8E5h2gjzcfutEvK4VR5a2T8+eJR/gcOe2MkYg7NPSQXMiTRSL/Mkp6mjkqDzcfdwxGI+WtEDMWCUzEx8iB0TseGuWJsOhI/5LjHNfae6vLbrNVqMKxs8oNM+IlflZaaQaujkCZzCgfgZaP5KgNspaDrMTgDfSxebwi5rSkpFchxPz8UsrvQOFgzjTtx/676mHe7d8LUfngFZW+hvMyrsbPt5FZ5AjG4XweqLb6IEGlp+GxZLvRLp1+gVIQUMqDCr2cNOq1mUJRHwbj1Gc8f5dQnraatibugPzaTyZ7S8e8DuvAy/pVfn9Wo6l05qgbnX1LdVSIFkqmx0VPZ6mAsZjjiX47L9YvKUwvWf9MS/A+MyJeKgcL3qZ/pFFPsr48v8TB+jrYaFakHCxWnR9UnQL404PXH9kTjkeXOsJIA4HyCx68Uarf86ylxW0+qxrn5juDZxfTbBN4bq/p81sKf9pOCA7/GE0T9Ff+2HUTsdydYsQIuS1WRtRE7wyZWrjH1pogKNE3MdzEyDz1yVHL1kQqq9b+Mqt5z+0wuEkfBLxOLSO9ivb3LgdaDuALpD7KuLErsn8Hv9Gn1ueBCXU1TFrqr5WJC2IbaPBX2uXXlJGVlpiR/bnlkfjP2Ic+/pIzLtpeuW5nAlItruIOM8oqv7JrHqOGfkvJYP7oYoPY7sbvtfbJ2Jq75LzMLxzz4X2U3QRj3ZP54GjpJ+6y/yTEUbWl6jlTyoPegl87WlQ==
      UserRole:
        type: string
        example: Underwriter
      UserPrimaryObjectId:
        type: integer
        example: 2152823
      UserPrimaryObjectType:
        type: string
        example: ENTITY         